import 'extensions/last_or_default_test.dart' as last_or_default_test;
import 'extensions/to_linked_hash_map_test.dart' as to_linked_hash_map_test;
import 'extensions/concat_all_test.dart' as concat_all_test;
import 'extensions/except_test.dart' as except_test;
import 'extensions/cartesian_select_test.dart' as cartesian_select_test;
import 'extensions/interleave_all_test.dart' as interleave_all_test;
import 'extensions/move_test.dart' as move_test;
import 'extensions/sequence_equals_select_test.dart'
    as sequence_equals_select_test;
import 'extensions/group_by_value_test.dart' as group_by_value_test;
import 'extensions/sum_test.dart' as sum_test;
import 'extensions/consume_test.dart' as consume_test;
import 'extensions/cartesian_test.dart' as cartesian_test;
import 'extensions/union_test.dart' as union_test;
import 'extensions/assert_all_test.dart' as assert_all_test;
import 'extensions/single_or_default_test.dart' as single_or_default_test;
import 'extensions/try_aggregate_right_test.dart' as try_aggregate_right_test;
import 'extensions/batch_test.dart' as batch_test;
import 'extensions/insert_test.dart' as insert_test;
import 'extensions/assert_count_test.dart' as assert_count_test;
import 'extensions/randomize_test.dart' as randomize_test;
import 'extensions/first_where_or_default_test.dart'
    as first_where_or_default_test;
import 'extensions/average_test.dart' as average_test;
import 'extensions/exclude_test.dart' as exclude_test;
import 'extensions/count_by_test.dart' as count_by_test;
import 'extensions/fill_forward_test.dart' as fill_forward_test;
import 'extensions/try_insert_test.dart' as try_insert_test;
import 'extensions/pairwise_test.dart' as pairwise_test;
import 'extensions/lag_select_test.dart' as lag_select_test;
import 'extensions/permutations_test.dart' as permutations_test;
import 'extensions/lead_select_test.dart' as lead_select_test;
import 'extensions/memoize_test.dart' as memoize_test;
import 'extensions/take_last_test.dart' as take_last_test;
import 'extensions/pad_end_test.dart' as pad_end_test;
import 'extensions/at_most_test.dart' as at_most_test;
import 'extensions/aggregate_select_test.dart' as aggregate_select_test;
import 'extensions/then_by_descending_test.dart' as then_by_descending_test;
import 'extensions/ends_with_test.dart' as ends_with_test;
import 'extensions/interleave_test.dart' as interleave_test;
import 'extensions/intersect_test.dart' as intersect_test;
import 'extensions/concat_test.dart' as concat_test;
import 'extensions/to_splay_tree_map_test.dart' as to_splay_tree_map_test;
import 'extensions/take_every_test.dart' as take_every_test;
import 'extensions/insert_or_append_all_test.dart' as insert_or_append_all_test;
import 'extensions/join_map_test.dart' as join_map_test;
import 'extensions/default_if_empty_test.dart' as default_if_empty_test;
import 'extensions/default_range_if_empty_test.dart'
    as default_range_if_empty_test;
import 'extensions/insert_all_test.dart' as insert_all_test;
import 'extensions/exclude_range_test.dart' as exclude_range_test;
import 'extensions/compare_count_test.dart' as compare_count_test;
import 'extensions/flatten_test.dart' as flatten_test;
import 'extensions/aggregate_right_test.dart' as aggregate_right_test;
import 'extensions/batch_select_test.dart' as batch_select_test;
import 'extensions/exclude_at_test.dart' as exclude_at_test;
import 'extensions/skip_last_test.dart' as skip_last_test;
import 'extensions/to_stream_test.dart' as to_stream_test;
import 'extensions/of_type_test.dart' as of_type_test;
import 'extensions/distinct_test.dart' as distinct_test;
import 'extensions/await_all_test.dart' as await_all_test;
import 'extensions/try_aggregate_test.dart' as try_aggregate_test;
import 'extensions/starts_with_test.dart' as starts_with_test;
import 'extensions/try_single_or_default_test.dart'
    as try_single_or_default_test;
import 'extensions/reverse_test.dart' as reverse_test;
import 'extensions/min_test.dart' as min_test;
import 'extensions/insert_or_append_test.dart' as insert_or_append_test;
import 'extensions/zip_test.dart' as zip_test;
import 'extensions/order_by_test.dart' as order_by_test;
import 'extensions/split_test.dart' as split_test;
import 'extensions/assert_any_test.dart' as assert_any_test;
import 'extensions/lag_test.dart' as lag_test;
import 'extensions/await_any_test.dart' as await_any_test;
import 'extensions/to_hash_map_test.dart' as to_hash_map_test;
import 'extensions/append_all_test.dart' as append_all_test;
import 'extensions/first_or_default_test.dart' as first_or_default_test;
import 'extensions/try_single_where_or_default_test.dart'
    as try_single_where_or_default_test;
import 'extensions/prescan_test.dart' as prescan_test;
import 'extensions/all_test.dart' as all_test;
import 'extensions/fill_missing_test.dart' as fill_missing_test;
import 'extensions/scan_test.dart' as scan_test;
import 'extensions/pad_start_test.dart' as pad_start_test;
import 'extensions/prepend_test.dart' as prepend_test;
import 'extensions/element_at_or_default_test.dart'
    as element_at_or_default_test;
import 'extensions/prepend_all_test.dart' as prepend_all_test;
import 'extensions/non_null_test.dart' as non_null_test;
import 'extensions/try_insert_all_test.dart' as try_insert_all_test;
import 'extensions/repeat_test.dart' as repeat_test;
import 'extensions/group_by_test.dart' as group_by_test;
import 'extensions/aggregate_right_select_test.dart'
    as aggregate_right_select_test;
import 'extensions/random_subset_test.dart' as random_subset_test;
import 'extensions/select_test.dart' as select_test;
import 'extensions/to_map_test.dart' as to_map_test;
import 'extensions/lead_test.dart' as lead_test;
import 'extensions/at_least_test.dart' as at_least_test;
import 'extensions/select_many_test.dart' as select_many_test;
import 'extensions/between_test.dart' as between_test;
import 'extensions/then_by_test.dart' as then_by_test;
import 'extensions/aggregate_test.dart' as aggregate_test;
import 'extensions/append_test.dart' as append_test;
import 'extensions/index_test.dart' as index_test;
import 'extensions/count_test.dart' as count_test;
import 'extensions/group_select_value_test.dart' as group_select_value_test;
import 'extensions/order_by_descending_test.dart' as order_by_descending_test;
import 'extensions/sequence_equals_test.dart' as sequence_equals_test;
import 'extensions/partition_test.dart' as partition_test;
import 'extensions/fill_backward_test.dart' as fill_backward_test;
import 'extensions/max_test.dart' as max_test;
import 'extensions/last_where_or_default_test.dart'
    as last_where_or_default_test;
import 'extensions/single_where_or_default_test.dart'
    as single_where_or_default_test;
import 'extensions/subsets_test.dart' as subsets_test;
import 'extensions/group_join_test.dart' as group_join_test;
import 'extensions/group_select_test.dart' as group_select_test;
import 'utility/tuple_8_test.dart' as tuple_8_test;
import 'utility/tuple_3_test.dart' as tuple_3_test;
import 'utility/tuple_test.dart' as tuple_test;
import 'utility/tuple_1_test.dart' as tuple_1_test;
import 'utility/tuple_4_test.dart' as tuple_4_test;
import 'utility/tuple_2_test.dart' as tuple_2_test;
import 'utility/tuple_7_test.dart' as tuple_7_test;
import 'utility/tuple_6_test.dart' as tuple_6_test;
import 'utility/tuple_0_test.dart' as tuple_0_test;
import 'utility/tuple_5_test.dart' as tuple_5_test;
import 'utility/tuple_9_test.dart' as tuple_9_test;
import 'factories/repeat_iterable_test.dart' as repeat_iterable_test;
import 'factories/range_iterable_test.dart' as range_iterable_test;
import 'string_extension_test.dart' as string_extension_test;

void main() {
  last_or_default_test.main();
  to_linked_hash_map_test.main();
  concat_all_test.main();
  except_test.main();
  cartesian_select_test.main();
  interleave_all_test.main();
  move_test.main();
  sequence_equals_select_test.main();
  group_by_value_test.main();
  sum_test.main();
  consume_test.main();
  cartesian_test.main();
  union_test.main();
  assert_all_test.main();
  single_or_default_test.main();
  try_aggregate_right_test.main();
  batch_test.main();
  insert_test.main();
  assert_count_test.main();
  randomize_test.main();
  first_where_or_default_test.main();
  average_test.main();
  exclude_test.main();
  count_by_test.main();
  fill_forward_test.main();
  try_insert_test.main();
  pairwise_test.main();
  lag_select_test.main();
  permutations_test.main();
  lead_select_test.main();
  memoize_test.main();
  take_last_test.main();
  pad_end_test.main();
  at_most_test.main();
  aggregate_select_test.main();
  then_by_descending_test.main();
  ends_with_test.main();
  interleave_test.main();
  intersect_test.main();
  concat_test.main();
  to_splay_tree_map_test.main();
  take_every_test.main();
  insert_or_append_all_test.main();
  join_map_test.main();
  default_if_empty_test.main();
  default_range_if_empty_test.main();
  insert_all_test.main();
  exclude_range_test.main();
  compare_count_test.main();
  flatten_test.main();
  aggregate_right_test.main();
  batch_select_test.main();
  exclude_at_test.main();
  skip_last_test.main();
  to_stream_test.main();
  of_type_test.main();
  distinct_test.main();
  await_all_test.main();
  try_aggregate_test.main();
  starts_with_test.main();
  try_single_or_default_test.main();
  reverse_test.main();
  min_test.main();
  insert_or_append_test.main();
  zip_test.main();
  order_by_test.main();
  split_test.main();
  assert_any_test.main();
  lag_test.main();
  await_any_test.main();
  to_hash_map_test.main();
  append_all_test.main();
  first_or_default_test.main();
  try_single_where_or_default_test.main();
  prescan_test.main();
  all_test.main();
  fill_missing_test.main();
  scan_test.main();
  pad_start_test.main();
  prepend_test.main();
  element_at_or_default_test.main();
  prepend_all_test.main();
  non_null_test.main();
  try_insert_all_test.main();
  repeat_test.main();
  group_by_test.main();
  aggregate_right_select_test.main();
  random_subset_test.main();
  select_test.main();
  to_map_test.main();
  lead_test.main();
  at_least_test.main();
  select_many_test.main();
  between_test.main();
  then_by_test.main();
  aggregate_test.main();
  append_test.main();
  index_test.main();
  count_test.main();
  group_select_value_test.main();
  order_by_descending_test.main();
  sequence_equals_test.main();
  partition_test.main();
  fill_backward_test.main();
  max_test.main();
  last_where_or_default_test.main();
  single_where_or_default_test.main();
  subsets_test.main();
  group_join_test.main();
  group_select_test.main();
  tuple_8_test.main();
  tuple_3_test.main();
  tuple_test.main();
  tuple_1_test.main();
  tuple_4_test.main();
  tuple_2_test.main();
  tuple_7_test.main();
  tuple_6_test.main();
  tuple_0_test.main();
  tuple_5_test.main();
  tuple_9_test.main();
  repeat_iterable_test.main();
  range_iterable_test.main();
  string_extension_test.main();
}
