name: darq
description: A port of functional LINQ from the .NET library.
version: 0.1.0
author: andrew.ackerman <andrew.ackie@gmail.com>
homepage: https://github.com/andrewackerman/darq
repository: https://github.com/andrewackerman/darq
issue_tracker: https://github.com/andrewackerman/darq/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies: 
  test: ^1.6.4