name: darq
description: The power of lazy-evaluated enumerables in your hands! (A port of functional LINQ from the .NET library.)
version: 1.0.0-dev.1
homepage: https://github.com/andrewackerman/darq
repository: https://github.com/andrewackerman/darq
issue_tracker: https://github.com/andrewackerman/darq/issues

environment:
  sdk: ">=2.12.0 <3.0.0" 

dev_dependencies: 
  test: ^1.16.4
  pedantic: ^1.10.0 
  test_coverage: ^0.5.0