name: darq
description: The power of lazy-evaluated enumerables in your hands! (A port of functional LINQ from the .NET library.)
version: "2.0.0"
homepage: https://github.com/abion47/darq
repository: https://github.com/abion47/darq
issue_tracker: https://github.com/abion47/darq/issues

environment:
  sdk: ">=3.0.0 <4.0.0" 

dev_dependencies: 
  lints: ^2.1.0
  test: ^1.24.3
