name: darq
description: The power of lazy-evaluated enumerables in your hands! (A port of functional LINQ from the .NET library.)
version: "1.2.0"
homepage: https://github.com/abion47/darq
repository: https://github.com/abion47/darq
issue_tracker: https://github.com/abion47/darq/issues

environment:
  sdk: ">=2.12.0 <3.0.0" 

dev_dependencies: 
  test: ^1.16.4
  pedantic: ^1.10.0 