name: darq
description: The power of lazy-evaluated enumerables in your hands! (A port of functional LINQ from the .NET library.)
version: 0.5.1+1
homepage: https://github.com/andrewackerman/darq
repository: https://github.com/andrewackerman/darq
issue_tracker: https://github.com/andrewackerman/darq/issues

environment:
  sdk: ">=2.7.1 <3.0.0"

dev_dependencies: 
  test: ^1.15.0
  pedantic: ^1.9.0
  test_coverage: ^0.5.0