name: darq
description: The power of lazy-evaluated enumerables in your hands! (A port of functional LINQ from the .NET library.)
version: 0.3.1
author: andrew.ackerman <andrew.ackie@gmail.com>
homepage: https://github.com/andrewackerman/darq
repository: https://github.com/andrewackerman/darq
issue_tracker: https://github.com/andrewackerman/darq/issues

environment:
  sdk: ">=2.6.1 <3.0.0"

dev_dependencies: 
  test: ^1.6.4
  pedantic: ^1.7.0