# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: Build Action

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Install coverage tools
        run: dart pub global activate coverage

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test --coverage="coverage"

      - name: Generate code coverage report
        run: format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.lcov
          token: ${{ secrets.CODECOV_API_TOKEN_2 }}
        # run: curl -s https://codecov.io/bash | bash
